version: 0.2

phases:
  install:
    commands:
      - echo pip initial version ...
      - python -m pip --version
      - echo python3 initial version in this Docker image ...
      - python3 --version
      - echo Download pip ...
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - echo Install pip ...
      - python3 get-pip.py
      - echo pip installed ...
      - echo Installed Flask ...
      - python3 -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
